<?php 
date_default_timezone_set('Asia/Manila');
require_once 'conn.inc.php';
//require_once 'dbconn.inc.php';
//include required phpmailer files
require 'PHPMailer.php';
require 'SMTP.php';
require 'Exception.php';
//Define name spaces
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

$user_id = $_POST['ID'];
$date = date('F j, Y g:i a');

$copy_query = "
SELECT * FROM `user_request` WHERE `ID` = ?;
";
$stmt = $conn->prepare($copy_query);
$stmt->execute([$user_id]);
$row = $stmt->fetch();

if($row['requestRole']=='Admin'){
    $insert_query = "
    INSERT INTO `users`( `username`, `email`, `password`, `role`) VALUES (?,?,?,?)
    ";
    $result2 = $conn->prepare($insert_query)->execute(array($row['username'], $row['email'], $row['password'], $row['requestRole']));
}
/*
if($row['requestRole']=='User'){
    $insert_query = "
    INSERT INTO `users`( `username`, `email`, `password`, `role`) VALUES (?,?,?,?)
    ";
    $result2 = $conn->prepare($insert_query)->execute(array($row['username'], $row['email'], $row['password'], $row['requestRole']));
}else{
    $insert_query = "
    UPDATE `users` SET `role`='Admin' WHERE `username` = ?
    ";
    $result2 = $conn->prepare($insert_query)->execute(array($row['username']));
}*/
if($result2){
    //Create instance of phpmailer
    $mail = new PHPMailer();
    //set mailer to use smtp
    $mail->isSMTP();
    //Define smtp host
    $mail->Host = "smtp.gmail.com";
    //enable smtp authentication
    $mail->SMTPAuth = "true";
    //set type of encription (ssl/tls)
    $mail->SMTPSecure = "tls";
    //set port to connect smtp
    $mail->Port = "587";
    //set gmail username
    $mail->Username = "hydroponic.adteam@gmail.com";
    //set gmail password
    $mail->Password = "hydroponic@2022";
    //set email subject
    if($row['requestRole'] == 'User'){
        $mail->Subject = "New User Registration Confirmation";
    }else{
        $mail->Subject = "New Admin Confirmation";
    }
    //set sender email
    $mail->setFrom("hydroponic.adteam@gmail.com");
    //email body
    
    if($row['requestRole'] == 'User'){
        $mail->Body = "Hi {$row['username']},

        Welcome to Hydroponic System Website! Good day and thank you for registering to our website. 

        This email is to confirm that your registration has been approved. You can now sign-in using your account.

        We're excited to share with you the real-time monitoring of automated indoor growing and how hydroponic grow system works. We provide a unique, automated agricultural system developed for urban growers, capable of adapting to any growing environment and handling any unexpected eventualities. Our main goal is to make cultivation easy and fun for everyone, with the highest performance for NFT-type of growing system.

        Regards,
        Hydroponic Admin Team

        Date reviewed: {$date}

        PLEASE DO NOT REPLY TO THIS MESSAGE. THIS IS AN AUTOGENERATED MAIL AND REPLIES TO THIS EMAIL ID ARE NOT ATTENDED TO.
        ";
    }else{
        $mail->Body = "Hi {$row['username']},

        This email is to confirm that you've been approved as one of the admin. You can now sign-in using your account and gain access to whole system, including the monitoring and viewing of data readings and controlling of the system.

        Your password is: {$row['password']}
        
        Regards,
        Hydroponic Admin Team

        Date reviewed: {$date}

        YOU RECEIVED THIS MESSAGE TO LET YOU KNOW ABOUT IMPORTANT CHANGES TO HYDROPONIC WEBSITE

        PLEASE DO NOT REPLY TO THIS MESSAGE. THIS IS AN AUTOGENERATED MAIL AND REPLIES TO THIS EMAIL ID ARE NOT ATTENDED TO.
        ";
    }
    //add recipient
    $mail->addAddress($row['email']);
    //send email
    if ($mail->send()){
        $main_query = "
        DELETE FROM `user_request` WHERE `ID` = '$user_id';
        ";

        $result = $conn->exec($main_query);
        //$result = mysqli_query($conn, $main_query);

        if($result==true)
        {
            $data = array(
            'status'=>'success',
            );
            echo json_encode($data);  
        }
        else
        {
            $data = array(
                'status'=>'failed',
            );
            echo json_encode($data);  
        } 
    }/*else{
        $data = array(
            'status'=>'failed',
        );
        echo json_encode($data);  
    }*/
    //closs smtp
    $mail->smtpClose();
}

?>